"""sites, device.site_id, credential api fields

Revision ID: 2523e7a92c2a
Revises: 843563cc7225
Create Date: 2026-06-04 12:53:46.260919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from netbuddy.db.types import EncryptedString
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2523e7a92c2a'
down_revision: Union[str, Sequence[str], None] = '843563cc7225'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enum-Wert 'api' ergänzen (Autogenerate erkennt das nicht). ALTER TYPE ... ADD VALUE
    # muss außerhalb einer Transaktion laufen → autocommit_block.
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE credential_protocol ADD VALUE IF NOT EXISTS 'api'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_site_name_active', 'site', ['name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.add_column('credential', sa.Column('base_url', sa.String(length=255), nullable=True))
    op.add_column('credential', sa.Column('api_token', EncryptedString(), nullable=True))
    op.add_column('credential', sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.alter_column('credential', 'username',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.add_column('device', sa.Column('site_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_device_site_id'), 'device', ['site_id'], unique=False)
    op.create_foreign_key(
        "fk_device_site_id", 'device', 'site', ['site_id'], ['id'], ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Enum-Wert 'api' bleibt erhalten (PostgreSQL kann Enum-Werte nicht entfernen).
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_device_site_id", 'device', type_='foreignkey')
    op.drop_index(op.f('ix_device_site_id'), table_name='device')
    op.drop_column('device', 'site_id')
    op.alter_column('credential', 'username',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.drop_column('credential', 'extra')
    op.drop_column('credential', 'api_token')
    op.drop_column('credential', 'base_url')
    op.drop_index('uq_site_name_active', table_name='site', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('site')
    # ### end Alembic commands ###
