"""arp_entry + host (Namensauflösung)

Revision ID: 3db5f7c39230
Revises: 9866fd865f56
Create Date: 2026-06-09 12:15:53.695177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3db5f7c39230'
down_revision: Union[str, Sequence[str], None] = '9866fd865f56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('host',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('mac', sa.String(length=32), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_host_ip_address'), 'host', ['ip_address'], unique=False)
    op.create_index(op.f('ix_host_mac'), 'host', ['mac'], unique=True)
    op.create_index(op.f('ix_host_name'), 'host', ['name'], unique=False)
    op.create_table('arp_entry',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('mac', sa.String(length=32), nullable=False),
    sa.Column('vlan_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arp_entry_device_id'), 'arp_entry', ['device_id'], unique=False)
    op.create_index(op.f('ix_arp_entry_ip_address'), 'arp_entry', ['ip_address'], unique=False)
    op.create_index(op.f('ix_arp_entry_mac'), 'arp_entry', ['mac'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_arp_entry_mac'), table_name='arp_entry')
    op.drop_index(op.f('ix_arp_entry_ip_address'), table_name='arp_entry')
    op.drop_index(op.f('ix_arp_entry_device_id'), table_name='arp_entry')
    op.drop_table('arp_entry')
    op.drop_index(op.f('ix_host_name'), table_name='host')
    op.drop_index(op.f('ix_host_mac'), table_name='host')
    op.drop_index(op.f('ix_host_ip_address'), table_name='host')
    op.drop_table('host')
    # ### end Alembic commands ###
