"""site mgmt_ip_template (Namens-zu-IP-Regel)

Revision ID: 46a0188f6ddd
Revises: 3db5f7c39230
Create Date: 2026-06-10 17:44:03.391775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46a0188f6ddd'
down_revision: Union[str, Sequence[str], None] = '3db5f7c39230'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('mgmt_ip_template', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site', 'mgmt_ip_template')
    # ### end Alembic commands ###
