"""lldp remote_mgmt_address

Revision ID: 720e220bdf56
Revises: 16614eab791f
Create Date: 2026-06-08 08:48:00.674363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '720e220bdf56'
down_revision: Union[str, Sequence[str], None] = '16614eab791f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lldp_neighbor', sa.Column('remote_mgmt_address', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lldp_neighbor', 'remote_mgmt_address')
    # ### end Alembic commands ###
