"""validation_check table

Revision ID: 843563cc7225
Revises: c31556efa8b2
Create Date: 2026-06-04 09:38:43.518468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '843563cc7225'
down_revision: Union[str, Sequence[str], None] = 'c31556efa8b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation_check',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('adapter_id', sa.String(length=64), nullable=False),
    sa.Column('capability', sa.String(length=64), nullable=False),
    sa.Column('command', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('row_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('raw_excerpt', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'capability', name='uq_validation_dev_cap')
    )
    op.create_index(op.f('ix_validation_check_adapter_id'), 'validation_check', ['adapter_id'], unique=False)
    op.create_index(op.f('ix_validation_check_device_id'), 'validation_check', ['device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_check_device_id'), table_name='validation_check')
    op.drop_index(op.f('ix_validation_check_adapter_id'), table_name='validation_check')
    op.drop_table('validation_check')
    # ### end Alembic commands ###
