"""vpn_tunnel relevant flag

Revision ID: 878bb2414311
Revises: d8cfa495b306
Create Date: 2026-06-10 17:52:10.416233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '878bb2414311'
down_revision: Union[str, Sequence[str], None] = 'd8cfa495b306'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vpn_tunnel', sa.Column('relevant', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vpn_tunnel', 'relevant')
    # ### end Alembic commands ###
