"""interface parent_name + vlan_id (Baumstruktur)

Revision ID: 8c7971315c66
Revises: 878bb2414311
Create Date: 2026-06-10 18:35:44.207922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c7971315c66'
down_revision: Union[str, Sequence[str], None] = '878bb2414311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interface', sa.Column('parent_name', sa.String(length=128), nullable=True))
    op.add_column('interface', sa.Column('vlan_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interface', 'vlan_id')
    op.drop_column('interface', 'parent_name')
    # ### end Alembic commands ###
