"""phase1 initial schema

Revision ID: c31556efa8b2
Revises: 
Create Date: 2026-05-15 18:31:24.666705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from netbuddy.db.types import EncryptedString
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c31556efa8b2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credential',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password', EncryptedString(), nullable=True),
    sa.Column('enable_password', EncryptedString(), nullable=True),
    sa.Column('ssh_port', sa.Integer(), server_default=sa.text('22'), nullable=False),
    sa.Column('snmp_community', EncryptedString(), nullable=True),
    sa.Column('snmp_version', sa.Enum('v1', 'v2c', 'v3', name='snmp_version'), nullable=True),
    sa.Column('snmpv3_user', sa.String(length=128), nullable=True),
    sa.Column('snmpv3_auth_protocol', sa.Enum('md5', 'sha', name='snmp_auth_protocol'), nullable=True),
    sa.Column('snmpv3_auth_key', EncryptedString(), nullable=True),
    sa.Column('snmpv3_priv_protocol', sa.Enum('des', 'aes', name='snmp_priv_protocol'), nullable=True),
    sa.Column('snmpv3_priv_key', EncryptedString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_credential_name_active', 'credential', ['name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('device',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('mgmt_ip', postgresql.INET(), nullable=False),
    sa.Column('vendor', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('os_version', sa.String(length=64), nullable=True),
    sa.Column('serial_number', sa.String(length=128), nullable=True),
    sa.Column('device_type', sa.Enum('switch', 'firewall', 'router', 'ap', 'other', name='device_type'), nullable=False),
    sa.Column('adapter_id', sa.String(length=64), nullable=False),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_hostname'), 'device', ['hostname'], unique=False)
    op.create_index(op.f('ix_device_mgmt_ip'), 'device', ['mgmt_ip'], unique=False)
    op.create_index('uq_device_hostname_active', 'device', ['hostname'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('discovery_run',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('triggered_by', sa.String(length=128), nullable=False),
    sa.Column('seed_devices', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('devices_found', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('status', sa.Enum('running', 'success', 'partial', 'failed', name='discovery_status'), server_default=sa.text("'running'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_credential',
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('credential_id', sa.UUID(), nullable=False),
    sa.Column('protocol', sa.Enum('ssh', 'snmp', name='credential_protocol'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['credential_id'], ['credential.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_id', 'credential_id', 'protocol')
    )
    op.create_table('interface',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('if_index', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('admin_status', sa.Enum('up', 'down', 'unknown', name='if_admin_status'), server_default=sa.text("'unknown'"), nullable=False),
    sa.Column('oper_status', sa.Enum('up', 'down', 'testing', 'unknown', name='if_oper_status'), server_default=sa.text("'unknown'"), nullable=False),
    sa.Column('mac_address', postgresql.MACADDR(), nullable=True),
    sa.Column('speed_mbps', sa.Integer(), nullable=True),
    sa.Column('mtu', sa.Integer(), nullable=True),
    sa.Column('interface_type', sa.String(length=64), nullable=True),
    sa.Column('last_polled', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interface_device_id'), 'interface', ['device_id'], unique=False)
    op.create_index('uq_interface_device_name_active', 'interface', ['device_id', 'name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('lldp_neighbor',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('local_device_id', sa.UUID(), nullable=False),
    sa.Column('local_interface_id', sa.UUID(), nullable=False),
    sa.Column('remote_chassis_id', sa.String(length=255), nullable=False),
    sa.Column('remote_port_id', sa.String(length=255), nullable=False),
    sa.Column('remote_port_description', sa.String(length=255), nullable=True),
    sa.Column('remote_system_name', sa.String(length=255), nullable=True),
    sa.Column('remote_system_description', sa.String(length=1024), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['local_device_id'], ['device.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['local_interface_id'], ['interface.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lldp_neighbor_local_device_id'), 'lldp_neighbor', ['local_device_id'], unique=False)
    op.create_index(op.f('ix_lldp_neighbor_local_interface_id'), 'lldp_neighbor', ['local_interface_id'], unique=False)
    op.create_table('mac_address_entry',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('interface_id', sa.UUID(), nullable=False),
    sa.Column('mac_address', postgresql.MACADDR(), nullable=False),
    sa.Column('vlan_id', sa.Integer(), nullable=True),
    sa.Column('entry_type', sa.Enum('dynamic', 'static', 'secure', name='mac_entry_type'), server_default=sa.text("'dynamic'"), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interface_id'], ['interface.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mac_address_entry_device_id'), 'mac_address_entry', ['device_id'], unique=False)
    op.create_index(op.f('ix_mac_address_entry_mac_address'), 'mac_address_entry', ['mac_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mac_address_entry_mac_address'), table_name='mac_address_entry')
    op.drop_index(op.f('ix_mac_address_entry_device_id'), table_name='mac_address_entry')
    op.drop_table('mac_address_entry')
    op.drop_index(op.f('ix_lldp_neighbor_local_interface_id'), table_name='lldp_neighbor')
    op.drop_index(op.f('ix_lldp_neighbor_local_device_id'), table_name='lldp_neighbor')
    op.drop_table('lldp_neighbor')
    op.drop_index('uq_interface_device_name_active', table_name='interface', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_interface_device_id'), table_name='interface')
    op.drop_table('interface')
    op.drop_table('device_credential')
    op.drop_table('discovery_run')
    op.drop_index('uq_device_hostname_active', table_name='device', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_device_mgmt_ip'), table_name='device')
    op.drop_index(op.f('ix_device_hostname'), table_name='device')
    op.drop_table('device')
    op.drop_index('uq_credential_name_active', table_name='credential', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('credential')
    # Autogenerate does not emit DROP TYPE for implicitly-created PG enums.
    for enum_name in (
        'credential_protocol',
        'device_type',
        'discovery_status',
        'if_admin_status',
        'if_oper_status',
        'mac_entry_type',
        'snmp_auth_protocol',
        'snmp_priv_protocol',
        'snmp_version',
    ):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
