"""site_subnet + vpn_tunnel

Revision ID: d8cfa495b306
Revises: 46a0188f6ddd
Create Date: 2026-06-10 17:51:25.909300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8cfa495b306'
down_revision: Union[str, Sequence[str], None] = '46a0188f6ddd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_subnet',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('cidr', postgresql.CIDR(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_subnet_site_id'), 'site_subnet', ['site_id'], unique=False)
    op.create_table('vpn_tunnel',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('remote_gateway', sa.String(length=64), nullable=True),
    sa.Column('is_up', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('local_subnets', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('remote_subnets', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vpn_tunnel_device_id'), 'vpn_tunnel', ['device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vpn_tunnel_device_id'), table_name='vpn_tunnel')
    op.drop_table('vpn_tunnel')
    op.drop_index(op.f('ix_site_subnet_site_id'), table_name='site_subnet')
    op.drop_table('site_subnet')
    # ### end Alembic commands ###
